### ISSUE TITLE
pip install version does not match

### ISSUE THREAD

**Issue by padeoe** [asuiu/pyxtension#13]
I installed pyxtension with pip, but it's weird the version shown doesn't match the real version.
I want to install version 1.11:
```
$ pip install pyxtension==1.11
Collecting pyxtension==1.11
Installing collected packages: pyxtension
Successfully installed pyxtension-1.0
```
then I use pip freeze to see the version:
```
$ pip freeze | grep pyxtension
pyxtension==1.0
```
It shows version 1.0.

**Comment by asuiu** [comment]
Hi @padeoe,
thanks for reporting issue.
Probably it happens because there's no 1.11 version. 
You can check the list of the released versions on [this link](https://pypi.org/manage/project/pyxtension/releases/).
I would suggest to get the lattest version of pyxtension which is 1.1.8
In the meantime I'll close this issue. Feel free to reopen if questions arises.
