### ISSUE TITLE
Compatibility issues with Python 3.8

### ISSUE THREAD

**Issue by kiranzo** [asuiu/pyxtension#27]
requirements.txt say "streamerate>=1.0.0", but latest version is not compatible with python 3.8 due to it using Python 3.10 syntax.

**Comment by asuiu** [comment]
Fixed in this commit: https://github.com/asuiu/pyxtension/commit/594dfc5660e2e24abf601bd556d22bf8bdc5ef77
Built & deployed new version on PyPi: https://pypi.org/project/pyxtension/1.16.11/

Also feel free to raise PRs.

@kiranzo thanks for contributing and creating issues!

Feel free to check and come back if it doesn't fix the issue

**Comment by asuiu** [comment]
> @asuiu Fixed, thanks! Problem is, I came across this error trying to use [bintablefile](https://github.com/eSAMTrade/bintablefile) library, and I still can't get it to work each time for different reason! Guess I'll just use gzipped parquet for my table data.

@kiranzo 
Just curious what errors you've got with the bintablefile. Feel free to add an issue on the project's github page, will be glad to try fix the usecase.

As a side note, instead of Parquet, I found ORC format slightly more friendly for the Python ecosystem.
Also don't apply the GZip over the Parquet/ORC, as these formats are performing internal compression AFAIK, and performance can degrade if compression is applied over the whole file (i.e. headers and metadata)

**Comment by kiranzo** [comment]
> > @asuiu Fixed, thanks! Problem is, I came across this error trying to use [bintablefile](https://github.com/eSAMTrade/bintablefile) library, and I still can't get it to work each time for different reason! Guess I'll just use gzipped parquet for my table data.
> 
> @kiranzo Just curious what errors you've got with the bintablefile. Feel free to add an issue on the project's github page, will be glad to try fix the usecase.
> 
> As a side note, instead of Parquet, I found ORC format slightly more friendly for the Python ecosystem. Also avoid applying the GZip over the Parquet/ORC, as these formats are performing internal compression AFAIK, and performance can degrade if compression is applied over the whole file (i.e. headers and metadata)

https://github.com/eSAMTrade/bintablefile/issues/6

I created it today. Thanks for the ORC suggestion, I'll look into it. Also, I created my parquet.gz with Pandas compression options, so it should be ok.
I test everything on a table that has uuid, filepath and 3 categorical columns (they were enums in PostgreSQL), so bintablefile doesn't suit my needs, unless I convert PostgreSQL enums to int-backed Python enums (we discussed it today, but it's something to consider in the future for now).
